### ISSUE TITLE
test

### ISSUE THREAD

**Issue by ehsmohammadi** [ehsmohammadi/Atabat#1]

**Comment by ehsmohammadi** [comment]
this issue was created for testing

**Comment by ehsmohammadi** [comment]
;lasd;lka;sldk;alskd;alsk;dalsk;d

**Comment by fAllahyari** [comment]
please send again 
@ehsmohammadi

**Comment by ehsmohammadi** [comment]
@fAllahyari  what ??

**Comment by fAllahyari** [comment]
https://webapps.stackexchange.com/questions/90668/how-to-enable-desktop-notifications-for-gmail
یک لینک بالای همون ستینگ بود که باید کلیک میکردیم
که این افزونه را نصب میکرد
Allow-Control-Allow-Origin
الان درست شد.
ممنون
@ehsmohammadi
