### ISSUE TITLE
Create new and clean seed data 

### ISSUE THREAD

**Issue by FeSaeedi** [ehsmohammadi/Atabat#101]
⌚️ Estimated : 8 hours
⌚️ Actual : 8 hours

**Comment by msabeti** [comment]
⌚️ actual : 8 hours

**Comment by msabeti** [comment]
Data generated script should be generate from following tables.(Related file Group seed data)
Applicants
ApplicantTransaction
ArzTransferenceDocs
ArzTransferenceDocsCover
Covers
Covers_Groups
ContactInfo
EPaymentLog
FormContent
FormResponse
Groups
GeneralApplicant
GroupFacilityApplicant
GroupStateLog
ManualPayment
PersonLog
PaymentLog
PassportInfo
Persons 
StudentApplicant

**Comment by mmahabadi** [comment]
⌚️ actual: 3 Hours

**Comment by mmahabadi** [comment]
These Tables should be involved.
ArzTransferenceDocs
ArzTransferenceDocsCover

**Comment by ehsmohammadi** [comment]
All thing in order now ...
