### ISSUE TITLE
Refactor systemSetting

### ISSUE THREAD

**Issue by fAllahyari** [ehsmohammadi/Atabat#110]
remove Item from systemSetting To RegistrationTimePeriodSetting

**Comment by ehsmohammadi** [comment]
@fAllahyari  tel to responsible person which one of fields you want to move from system setting to period setting

**Comment by fAllahyari** [comment]
لطفا موارد زیر در پنل ادمین در تنظیمات دوره اضافه شود و در پروژه منیجر از دوره خوانده شود .
IsCreateTaskAfterFinalRegistration bool
PrintPersonPictureInManifesto bool
MaxAppCount int
PrintBarcode bool
dayAddefromNowForDispatchDate int
PlakPrintDate datetime
DeliveryExpireDateTime datetime
RespiteDayToDelivery int
ManagerSginInPermission bool
SpecialMellatExpireDate datetime

**Comment by mmahabadi** [comment]
@fAllahyari please determine the type of fields.

**Comment by fAllahyari** [comment]
@mehabadi 
کامنت قبلی ویرایش شد و توضیحات نیز در جدول
systemSetting
وجود دارد

**Comment by mmahabadi** [comment]
Add payment type to the setting
