### ISSUE TITLE
کاربرد اجازه ورود در پنل مدیریتی در  قسمت تنظیمات چیست ؟

### ISSUE THREAD

**Issue by Morebopo** [ehsmohammadi/Atabat#130]

**Comment by mmahabadi** [comment]
@msabeti this setting is available in Period setting and I have no idea about it. I guess you use it in the Manager System. Please enlighten us.

**Comment by msabeti** [comment]
@Morebopo @mehabadi 
Haj organization's request is for use and availability of the Manager panel that is customizable by the administrator

**Comment by ehsmohammadi** [comment]
Its not working , we must fixed the bug when removing this flag from admin

**Comment by msabeti** [comment]
@Morebopo 
Is this field depends on Registration Time Period?

**Comment by Morebopo** [comment]
@msabeti @ehsmohammadi 
پیرو اعلام تغییرات انجام شده این قابلیت در تعریف بازه زمانی (دوره) گذاشته شده است

**Comment by ehsmohammadi** [comment]
moved jira
