### ISSUE TITLE
زمان عدم امکان تحویل مدارک در کارگزاری در منوی تنظیمات 

### ISSUE THREAD

**Issue by Morebopo** [ehsmohammadi/Atabat#132]
با توجه به اینکه بر حسب دوره ثبت نام ها انجام می شود، وجود این گزینه کاربردی دارد !؟

**Comment by ehsmohammadi** [comment]
@Morebopo need meeting

**Comment by ehsmohammadi** [comment]
Remove this option from global setting and show the proper option in period setting i think its missing ...
