### ISSUE TITLE
نوع وارد کردن تاریخ بازگشت دراطلاعات اعزام در قسمت ثبت نام

### ISSUE THREAD

**Issue by Morebopo** [ehsmohammadi/Atabat#133]
درخواست :
  وارد کردن تاریخ از روی تقویم به جای وارد کردن تاریخ به صورت دستی

**Comment by fAllahyari** [comment]
Done in 4 hour

**Comment by Morebopo** [comment]
تاریخ خروج از مرز و بازگشت از روی تقویم انتخاب شود
در داخل تقویم ، تاریخ های قبل از روز جاری امکان انتخاب نداشته باشد و همچنین فقط و فقط روزها و ماه هایی که در بازه ی انتخاب هستند می بایست فعال باشند  تا به اشتباه تاریخ های خارج از بازه انتخاب نشود

**Comment by ehsmohammadi** [comment]
moved jira
