### ISSUE TITLE
حذف پیام "تردد زائرین انفرادی از مرزهای زمینی به کشور عراق، ممنوع می باشد" 

### ISSUE THREAD

**Issue by Morebopo** [ehsmohammadi/Atabat#134]
آدرس : در قسمت تائید اطلاعات، در قسمت ثبت نام

مقرر شد چنین مواردی در مرحله ثبت اطلاعات در قسمت "موارد قابل توجه :" خود سازمان از طریق پنل ادمین اطلاعات وارد کنند

**Comment by ehsmohammadi** [comment]
@Morebopo  need a design meeting

**Comment by ehsmohammadi** [comment]
its will be resolve in proper issue #9

**Comment by Morebopo** [comment]
@fAllahyari @FeSaeedi 
حذف پیام "تردد زائرین انفرادی از مرزهای زمینی به کشور عراق، ممنوع می باشد"

**Comment by ehsmohammadi** [comment]
moved jira
