### ISSUE TITLE
مشخص نبودن دوره ی انتخابی در حین ثبت نام

### ISSUE THREAD

**Issue by Morebopo** [ehsmohammadi/Atabat#136]
با توجه به اینکه در حال حاضر کاربر با انتخاب دوره ی مورد نظر اقدام به ثبت نام می کند، در حین ادامه فرایند ثبت نام دوره ی انتخاب شده مشخص نیست

**Comment by fAllahyari** [comment]
انجام شد

**Comment by fAllahyari** [comment]
Done
