### ISSUE TITLE
 نمایش فرم های تعریف شده در دوره های مختلف

### ISSUE THREAD

**Issue by Morebopo** [ehsmohammadi/Atabat#137]
در حال حاضر فرم های تعریف شده در پنل ادمین با عوض کردن دوره ها در "لیست فرم ها" نمایش داده می شود که با توجه به اینکه هر دوره فرم مخصوص به خودش را ممکن است داشته باشد، نباید این اتفاق صورت پذیرد

**Comment by ehsmohammadi** [comment]
@Morebopo  need session for this issue

**Comment by ehsmohammadi** [comment]
@Morebopo  you describe it for haj organization how can they solve the problem bu existed component

**Comment by ehsmohammadi** [comment]
moved jira
