### ISSUE TITLE
تغییر در فرم اطلاعات پزشکی در قسمت ثبت نام 

### ISSUE THREAD

**Issue by Morebopo** [ehsmohammadi/Atabat#139]
درخواست :
به این صورت باشد که از فرد سوال شود

آیا بیماری خاصی دارید ؟ بله    خیر 
به صورت رادیو باتون و دیفالت سلکت نشده باشد و در صورت انتخاب بله فرم دریافت اطلاعات پزشکی وارد شود
به عبارتی گزینه بله و خیر به صورت دیفالت انتخاب نشده باشد

**Comment by fAllahyari** [comment]
@ehsmohammadi 
این تغییر باید در ادمین و هنگام تعریف فرم صورت بگیرد.

**Comment by fAllahyari** [comment]
@ehsmohammadi 
در ادمین باید متدی جهت پاک کردن اطلاعات موجود ، نوشته شود
به عنوان مثال فردی دفعه اول تیک "آیا بیماری خاصی دارید"
را میزد و بعد در ویرایش تیک را برمیدارد.

**Comment by ehsmohammadi** [comment]
moved jira
