### ISSUE TITLE
در صفحه داشبورد هر کجا عدد مانیفست ذکر شده است، تعداد کل افراد آن مانیفست ها درج شود

### ISSUE THREAD

**Issue by Morebopo** [ehsmohammadi/Atabat#143]
![image](https://user-images.githubusercontent.com/28531483/28308473-882147b8-6bbb-11e7-96d5-f48f309b8688.png)

**Comment by Morebopo** [comment]
Dear @jafarzadeh @ehsmohammadi @mehabadi 
Do you agree with their request?!!
In my opinion we need to remove some parts of dashboard panel and prepare Haj Organization with the proper reports.

**Comment by ehsmohammadi** [comment]
moved jira
