### ISSUE TITLE
عدم نمایش گزینه چاپ و ویرایش مجوز تردد 

### ISSUE THREAD

**Issue by Morebopo** [ehsmohammadi/Atabat#156]
گزینه چاپ و ویرایش مجوز تردد تا اطلاع ثانوی در منو سماح نمایش داده نشود

**Comment by fAllahyari** [comment]
در ادمین، در قسمت تنظیمات دوره، گزینه
تاریخ شروع چاپ مجوز تردد
باعث نمایش این منو در سماح میشود

**Comment by ehsmohammadi** [comment]
moved jira
