### ISSUE TITLE
عدم حذف سرویس با توجه به نمایش پیام "اطلاعات با موفقیت حذف شدند

### ISSUE THREAD

**Issue by Morebopo** [ehsmohammadi/Atabat#158]
باگ : 
در قسمت سرویس، به عنوان مثال حذف سرویس هلال احمر پیغام "اطلاعات با موفقیت حذف شدند." می دهد ولی در عمل سرویس حذف نمی شود

**Comment by ehsmohammadi** [comment]
moved jira
