### ISSUE TITLE
Define Period Settings

### ISSUE THREAD

**Issue by mmahabadi** [ehsmohammadi/Atabat#16]
Please indicate the proper period settings on the part of application you work.

@msabeti @fAllahyari @FeSaeedi @emoradi

**Comment by FeSaeedi** [comment]
SpecialMellatExpireDate: DateTime
OpenRegisterOnly4Agents: DateTime
RequiredEstelamNajaRegister: bool
RequiredEstelamCodeMeli: bool
RequiredEstelamNaja: bool

**Comment by fAllahyari** [comment]
CloseRegisterationTime datetime
CloseEditTime datetime

**Comment by FeSaeedi** [comment]
DayCountAfterViza int
الان دو تا فیلد وجود داره:
MaxAppCount
MaxAppCountNotSpecial
فکر کنم یکی برای هر دوره کافی
MaxAppCount int
@fAllahyari  درسته ؟

**Comment by mmahabadi** [comment]
I guess you need to know the number of people in each group in each Period.
I it correct?
@FeSaeedi @fAllahyari

**Comment by mmahabadi** [comment]
Do you need to set state of the payment? (de/activate Payment)
You need to set payment type for each period, I mean EPayment, Manual Payment and Combined.
@fAllahyari @FeSaeedi

**Comment by FeSaeedi** [comment]
به نظرم در هر دوره ماکزیمم تعداد افراد هر گروه لازم است
الان تنظیمات لازم برای پرداخت در دوره است
@fAllahyari  نظر شما چیه؟

**Comment by msabeti** [comment]
DeliveryExpireDateTime
