### ISSUE TITLE
فراهم کردن امکان ثبت نام بدون پرداخت هزینه در ادمین

### ISSUE THREAD

**Issue by Morebopo** [ehsmohammadi/Atabat#163]
درخواست : 
با توجه به  عدم مشخص بودن قیمت ارز و بیمه و ... این امکان برای ادمین سیستم فراهم باشد تا بتواند نسبت به تغییر  روند ثبت نام در مرحله پایانی اقدام کند

شایان به ذکر است درگاه ها و دکمه پرداخت و همچنین جدول قیمت های خدمات انتخابی نباید به متقاضی نمایش داده شود

**Comment by ehsmohammadi** [comment]
Moved to jira
