### ISSUE TITLE
Testing Form Builder

### ISSUE THREAD

**Issue by mmahabadi** [ehsmohammadi/Atabat#18]
Testing the Form Builder module on the web app.
The test comprise of following parts:

- [x] Display forms on web

- [x] Edit forms - Make it possible for applicants to edit their entries

**Comment by emoradi** [comment]
Status Test And Implementation Form Builder In The Manager Is Successful 
1H

**Comment by fAllahyari** [comment]
in register context test completed in 2 hours. by saeedi and allahyari

**Comment by fAllahyari** [comment]
in register context test completed in 2 hours. by saeedi and allahyari

**Comment by fAllahyari** [comment]
- [x] in register state show and insert salamat form

- [x] in register State show and update salamat form

- [x] in final register state show and update salamat form

**Comment by fAllahyari** [comment]
Test Form in SpecialDate and notSpecialDate

**Comment by ehsmohammadi** [comment]
If all your test was successful and was passed in your business process close the issue and good luck .. 
@emoradi @fAllahyari

**Comment by fAllahyari** [comment]
test complete. total time for all task in this issue for registeration context: 5 hour
