### ISSUE TITLE
Develop a mechanism for showing period in first page 

### ISSUE THREAD

**Issue by FeSaeedi** [ehsmohammadi/Atabat#2]
Estimated time : 16 hours/per person 

- [x] Selecting period for public user ( zaer ) 

- [x] Selecting period for agent user behalf of public user

**Comment by ehsmohammadi** [comment]
@fAllahyari @FeSaeedi  Please explain the main idea of design take picture and insert it here

**Comment by ehsmohammadi** [comment]
[Wedding invitation card.pdf](https://github.com/ehsmohammadi/Atabat/files/982354/Wedding.invitation.card.pdf)

**Comment by ehsmohammadi** [comment]
![passport](https://cloud.githubusercontent.com/assets/3368702/25790133/8ee00bac-33cb-11e7-83f5-e559cc7bc8bb.jpg)

**Comment by fAllahyari** [comment]
![periodinregister](https://cloud.githubusercontent.com/assets/27915531/25799974/8c860132-33fc-11e7-8b47-4d7a87ab53b4.jpg)

**Comment by fAllahyari** [comment]
currentRegistrationTimePeriod removed from globalsetting

**Comment by FeSaeedi** [comment]
Time : 12 hours/per person
