### ISSUE TITLE
Update Database

### ISSUE THREAD

**Issue by mmahabadi** [ehsmohammadi/Atabat#20]
Creating scripts to move from Atabat.visa95 to Atabat.visa.
It requires following preparations:

- [x] Compare Databases

- [x] Searching for comparison software

- [x] Create Scripts

- [ ] Insert initial data

- [x] Publish

- [x] Test

- [x] #41 

- [x] #35 

- [x] #54

- [x] #56

**Comment by mmahabadi** [comment]
We are going to use SQL Delta In order to compare databases.

**Comment by mmahabadi** [comment]
Change to local database:

- [ ] [dbo].[Agents]  - Insert [Transiant] [bit] NULL

- [ ] [dbo].[Boundries_Provinces]

- [ ] [dbo].[BankInformation]

- [ ] [dbo].[Covers_Groups]

- [ ] [dbo].[EpaymentLogs]

- [ ] [dbo].[Kargozaran_agent]

- [ ] [dbo].[News]
- [ ] [dbo].[SMSLogs]
- [ ] [dbo].[SpecialPayment]
- [ ] RegistrationTimePeriod 
- Users
- vw_People
sp__report_DashboardRegitrationInformation
- sp_DeleteCoversGroups
sp_EnserafJob

sp_Reports_ManifestData
sp_Reports_ManifestHeaders
sp_Reports_TehranManifestData

**Comment by mmahabadi** [comment]
Delete Database Tables:

- [ ] dbo].['951013-01$']

- [ ] [dbo].['951013-02$']

- [ ] [dbo].[ActiveAgent]

- [ ] [dbo].[ActiveAgent940625]

- [ ] [dbo].[Agents2]

- [ ] [dbo].[applicant_temp]

- [ ] [dbo].[AgentsBk940718]

- [ ] [dbo].[applicant_temp]

- [ ] [dbo].[applicantTempappcount]

- [ ] [dbo].[applicantTempnullcount]

- [ ] [dbo].[BCCIT2950602]

- [ ] [dbo].[Cities2]

- [ ] [dbo].[ErrorLog]

- [ ] [dbo].[Group_Facilities_Applicants_Backup_940616]

- [ ] [dbo].[PassportInfoLog]

- [ ] [dbo].[persons_940907_3]

- [ ] [dbo].[PersonsInfo]

- [ ] [dbo].[RequestLog]

- [ ] [dbo].[Samah]

- [ ] [dbo].[Sheet1$]

- [ ] [dbo].[tbl_0818_1945]

-[ ]  [tbl_940826_sendSms_48saat]

[tbl_ActiveAgent]

tbl * 

- TranactionDivide-PardakhteDovom
- Transaction951008
- transiantAgent
- UsersBc950514

Veiw : 

- sabteAhvalError
- vw_errorLog
- - vw_Province

sp : 

usp_ErrorLog_Insert

**Comment by mmahabadi** [comment]
Create manual migration Script:

- [ ] [dbo].[Applicants] remove [IsPassportConfirmed] [bit] NULL

- [ ] [dbo].[ArzValues]

- [ ] [dbo].[Facilities]

- [ ] [dbo].[Group_Facilities_Applicants]

- [ ] [dbo].[Groups]

- [ ] [dbo].[MergedFacilityLogs]

- [ ] [dbo].[MergedPaymentLogs]

- [ ] [dbo].[PaymentLogs]

- [ ] [dbo].[RegistrationTimePeriod]

RegistrationTimePeriod 

- vw_errorLog

- sp_GetArzTransferenceDocSummaries

**Comment by mmahabadi** [comment]
Tables should be deleted in server and local 
- tbl1  

- vw1

**Comment by mmahabadi** [comment]
- loser/finder --> default value script 
- Lost/FoundPersons --> default value script  
- RegistrationTimePeriod --> default value script for open for payment

**Comment by ehsmohammadi** [comment]
please notice fllowing points in query:

update [AtabatVisa].[dbo].[SystemSettings] set Value='2018/11/16 23:59:00' where id=21
go
update [AtabatVisa].[dbo].[SystemSettings] set Value='2018/11/16 23:59:00' where id=13
go
update [AtabatVisa].[dbo].[SystemSettings] set Value='2018/11/16 23:59:00' where id=14
go
update [AtabatVisa].[dbo].[RegistrationTimePeriods_Provinces] set IsActive=1 where RegistrationTimePeriodID=4
go
insert into [AtabatVisa].[dbo].[RegistrationTimePeriods_Provinces]([ProvinceID]
,[RegistrationTimePeriodID]
,[IsActive]) select ID,6,0 from [AtabatVisa].[dbo].Provinces where CountryID=1
go
update [AtabatVisa].[dbo].[RegistrationTimePeriods_Provinces] set IsActive=1 where RegistrationTimePeriodID=6 and ProvinceID in ( 19,15,17,20)
go
update [AtabatVisa].[dbo].[RegistrationTimePeriod] set IsActive=0 where id=4
go
update [AtabatVisa].[dbo].[SystemSettings] set Value='2018/11/16 23:59:00' where id=21
go
update [AtabatVisa].[dbo].[RegistrationTimePeriods_Provinces] set IsActive=1 where RegistrationTimePeriodID=4
go
insert into [AtabatVisa].[dbo].[RegistrationTimePeriods_Provinces]([ProvinceID]
,[RegistrationTimePeriodID]
,[IsActive]) select ID,6,0 from [AtabatVisa].[dbo].Provinces where CountryID=1
go
update [AtabatVisa].[dbo].[RegistrationTimePeriods_Provinces] set IsActive=1 where RegistrationTimePeriodID=6 and ProvinceID in ( 19,15,17,20)
go
update [AtabatVisa].[dbo].[RegistrationTimePeriod] set OpenForPayment=1, paymenttype=3 where id=6

**Comment by ehsmohammadi** [comment]
for delete registration data before state=2 this below query be helpfull
declare @gid int=1090694
delete FROM [AtabatVisa].[dbo].[Groups] where id=@gid

delete from Group_Facilities_Applicants where groupid=@gid

delete from paymentLogs where GroupID=@gid
delete from MergedGroups where MasterGroupID=@gid or SlaveGroupID=@gid
delete from GroupStateLogs where GroupID=@gid
delete from Groups_stations where GroupID=@gid
delete from covers_groups where GroupID=@gid
delete from GeneralApplicant where id=@gid
delete from Applicants where GroupID=@gid
