### ISSUE TITLE
How to implement health form 

### ISSUE THREAD

**Issue by fAllahyari** [ehsmohammadi/Atabat#22]
آیا فرم سلامت از ثبت نام قبلی بارگذاری شود یا نه؟؟؟

**Comment by Morebopo** [comment]
بله فرم سلامت بارگذاری شود

**Comment by Morebopo** [comment]
با توجه به نمایش اطلاعات گذرنامه و سایر اطلاعات، لطفاً فرم سلامت هم نمایش داده شود، با تشکر

**Comment by fAllahyari** [comment]
کد تصحیح شد و در ثبت نام جدید، فرم سلامت آخرین ثبت نام اگر وجودداشته باشد، نمایش داده میشود
اگر هم وجود نداشته باشد که فرم خام سلامت را نشان میدهد.
time: 1Hour
