### ISSUE TITLE
display which period form register by Agent

### ISSUE THREAD

**Issue by fAllahyari** [ehsmohammadi/Atabat#23]

**Comment by Morebopo** [comment]
![download](https://cloud.githubusercontent.com/assets/28531483/26026279/a160f534-380d-11e7-8a2b-cc730d726bbb.jpg)

**Comment by Morebopo** [comment]
همه ی دوره های فعال نمایش داده شود، و هر کارگزاری که انتخاب شد در صورتی دوره انتخابی برای کارگزار فعال نیست، پیام مناسب نمایش داده شود
