### ISSUE TITLE
Create Development and release branch 

### ISSUE THREAD

**Issue by ehsmohammadi** [ehsmohammadi/Atabat#24]
Dependencies : #2 #3 #4 #5 #6 #7 #8 #9 #11 #14 #17 #21

**Comment by ehsmohammadi** [comment]
I want to test my idea in infra structure repository then fix the proper bug then do it in development environment 
https://blogs.msdn.microsoft.com/visualstudioalmrangers/2015/09/16/version-control-walkthrough-branching-strategies-part-2-development-isolation-welcome-branching/
@emoradi

**Comment by ehsmohammadi** [comment]
I test the idea of branching on development and its sounds good for a little project i want to apply my test with conflict in one file and i want to spend some time to discover the versioning and other release stuff

**Comment by ehsmohammadi** [comment]
- I want to clear the project in source control first then by the means of clearing I wanted every one check in all change that they had made until today and freeze current state and so on ... 
- in this way i need to undo some change from dead Work space this the link that i found to manage this type of issue 
 http://stackoverflow.com/questions/1690351/how-to-undo-another-users-checkout-in-tfs-via-the-gui
and the tools 
https://marketplace.visualstudio.com/items?itemName=TFSPowerToolsTeam.MicrosoftVisualStudioTeamFoundationServer2015Power

**Comment by fAllahyari** [comment]
this addon help to know witch branch is open 
https://marketplace.visualstudio.com/items?itemName=mayerwin.RenameVisualStudioWindowTitle
windows title is change for example : Atabat.Visa-Dev\Atabat.Visa
@ehsmohammadi  @msabeti @mehabadi @FeSaeedi @emoradi

**Comment by ehsmohammadi** [comment]
The first step of this task was done and all member of team can develop new feature in development branch and support current version in main branch
