### ISSUE TITLE
Implement Agent in Period

### ISSUE THREAD

**Issue by mmahabadi** [ehsmohammadi/Atabat#30]
- Add RegistrationPermission(selective) field to AgentInPeriod Table

> If Agent was assigned to Period, It couldn't be removed. This means we should have soft remove for assigned agents. (IsActive field).

![image](https://cloud.githubusercontent.com/assets/7472245/25802231/a56069f4-3406-11e7-90ac-b1bc069f0a72.png)

**Comment by fAllahyari** [comment]
down in 2 H with 2 developer
