### ISSUE TITLE
Implement Facility in Period

### ISSUE THREAD

**Issue by mmahabadi** [ehsmohammadi/Atabat#35]
Dependencies : #7 , #15 
Depends on #24 

![image](https://cloud.githubusercontent.com/assets/7472245/25802712/c630193e-3408-11e7-8d3b-e4e6fd1b8e48.png)

⌚️ Task Duration: 1:45'

**Comment by mmahabadi** [comment]
Following Tables has been created.
- FacilityTypeVisa
- FacilityTypeInsurance
- FacilityTypeRedCrescent
- FacilityProvider
- FacilityTypeAgentRegistrationWage
- FacilityTypeAgentWage
- FacilityTypeInPeriod

And Following Tables has been altered:
- Facilities
- FacilityCost

Finally, the edmx file has been updated.

**Comment by mmahabadi** [comment]
The design should be rechecked.
It seems we missed a table.

![photo_2017-05-14_09-07-03](https://cloud.githubusercontent.com/assets/7472245/26031834/d8253ee8-3896-11e7-9c69-209002758675.jpg)

**Comment by ehsmohammadi** [comment]
in order to create and map database table and our bean clesses in inheritance situation we must take goo look at this link and forward comments
http://stackoverflow.com/questions/22263189/entity-framework-db-first-implement-inheritance

**Comment by mmahabadi** [comment]
In order to create Base Type in edmx file, we'd better set the base type then remove ID column from the class.

**Comment by fAllahyari** [comment]
rename DepencyId in FacilityTypeInPeriod Table To
RequiredFacilityId
because
FacilytAgentWage Depend On SingleVisa and MultipleVisa

**Comment by fAllahyari** [comment]
how to resolve IsRequired SingleVisa an multilpleVisa 
@ehsmohammadi @jafarzadeh

**Comment by ehsmohammadi** [comment]
@fAllahyari this question was discussed and answered by the time of meeting

**Comment by fAllahyari** [comment]
in registration context develop and test this case take 40 hours

خدمات انتخابی  و هززینه های آنها در 
اضافه کردن فرد به گروه
حذف فرد از گروه در وضعیت های 1 و  2
پیاده سازی و تست گردید
