### ISSUE TITLE
Implement Bank in period In Admin

### ISSUE THREAD

**Issue by ehsmohammadi** [ehsmohammadi/Atabat#37]
![image](https://cloud.githubusercontent.com/assets/7472245/25804304/5d201ee6-3410-11e7-893e-476f8afc5147.png)
 

depends on issue no #76

**Comment by mmahabadi** [comment]
⌚️ Estimated time: 24 H
🕥 Duration time: 36 H

**Comment by mmahabadi** [comment]
- [ ] Changing the structure of Period Setting to be make it possible to assign banks

- [ ] Developing Period setting in order to assign banks to each period

- [ ] Developing Banks Setting with new Design
