### ISSUE TITLE
check passport business for student

### ISSUE THREAD

**Issue by fAllahyari** [ehsmohammadi/Atabat#38]
for reserve border date for student how check passport?
agar student bashad passport mitavanad nadashte bashad va mogheye set tarikhe khoroj va marz ,expire date passport ra check mikonad. baraye student che kar konim?

**Comment by fAllahyari** [comment]
@emoradi

**Comment by FeSaeedi** [comment]
Time: 6 hour
زمانی که دانشجوی بدون پاسورت ثبت نام می کند، در رزرو مرز، تاریخ انقضای پاسپورت دانشجو را چک نمیکند.
زمانیکه اطلاعات پاسپورت دانشجو وارد می شود، اگر گروه تاریخ خروج داشته باشد آنگاه چک انجام می شود و در صورت مغایرت در ذخیره اطلاعات دانشجو خطا مربوط را نشان می دهد.
فرایند درسته؟

@fAllahyari 
@ehsmohammadi 
@Morebopo 
@jafarzadeh

**Comment by fAllahyari** [comment]
بله با صحبتی که با آقای بلبلپور داشتیم همین روند درست می باشد.
