### ISSUE TITLE
Question for letter number 2962 date 960217

### ISSUE THREAD

**Issue by fAllahyari** [ehsmohammadi/Atabat#39]
- مورد21 : در ایام عادی فرد متقاضی حتما باید درخواست روادید داشته باشد در نتیجه ویرایش درخواست روادید در ایام عادی بی معناست

- مورد 27 ایا منظور استان است یا شهر؟ در ثبت نام استان محل تحویل مدارک ندارم که ویرایش آن ایجاد گردد. ایا منظور این بوده که استان محل تحویل مدارک در صفحه اول بگزاریم و ویرایش یا منظور ویرایش شهر بوده؟

- مورد 11، در جابجایی کارگزاری، حق کارگزار به کارگزار دوم که در جابجایی ثبت میشود میرود، ایا این درست است؟

@fAllahyari 
مورد 21 : درخواستشان اشتباه بود، LOP صورت گرفت
@ehsmohammadi @FeSaeedi @fAllahyari 
مورد 27 : امکان تغییر استان محل سکونت قبل از تحویل مدارک به کارگزاری مهیا شود، که به مراتب این امر در تغییر استان محل تحویل مدارک نقش خواهد داشت.

**Comment by emoradi** [comment]
مورد 3 :

1. عملیات توزیع وجوه توسط کاربر سیستم اجرا شود یا به صورت اتوماتیک توسط سیستم اجرا شود

2. عملیات به ازای تحویل مدارک هر متقاضی انجام گیرد و یا به صورت کلی و در زمان خاص

3. شماره حساب های واریز مبالغ از چه منبع و به چه صورتی دریافت خواهد شد

@emoradi @ehsmohammadi 
جواب مورد 3 : 
1: توسط کاربر
2: انتهای فرایند درخواست روادید، یعنی تحویل مدارک توسط کارگزاری به متقاضی عملیات مربوط به توزیع وجوه به صورت دستی و توسط کاربر به تفکیک انجام پذیرد، به عبارتی یعنی کارگزار و استان و رابط هر کدام به جز بتوانند تسویه مالی رو با استان و حتی کارگزار خاص و یا دفتر مرکزی استان خاص انجام دهند
3:مقرر شد سازمان اعلام کند

**Comment by FeSaeedi** [comment]
: مورد 2 آیتم 3 
باید با توجه به وضعیت تعریف شود
همچنین برای بقیه خدمات نیز (بیمه و ویزا)باید به صورت مکتوب به ازای تمام وضعت ها ، نحو تقسیم هزینه تعیین شود
جدول کامل نیاز است!!

**Comment by ehsmohammadi** [comment]
مورد 9 
دقیقا توضیح داده شود که منظور چیست 

@msabeti 
پیرو صحبت هایی که در جلسه داشتیم همان موردی بود که خانم ثابتی عنوان کردند، باید بررسی کنیم در طول انجام فرایندها

**Comment by mmahabadi** [comment]
مورد 22 : 
در پنل مدیر سیستم، لاگ فعالیت هایی که برای دریافت روادیدزائر توسط هر کاربر انجام شده است برای هر زائر وجود داشته باشد.

لطفا مشخص شود اطلاعات مورد نیاز جهت نمایش به کاربر ادمین چیست؟

@mehabadi 
علاوه بر اطلاعاتی که در حال حاضر نمایش داده شده اند، اینکه که چه کاربری از کدام کارگزاری انصراف و ... انجاد داده است، نمایش داده شود

Dear @msabeti @FeSaeedi @fAllahyari @emoradi @ehsmohammadi ,
We need to talk about  a unique log system.

**Comment by mmahabadi** [comment]
مورد 24
در صفحه داشبورد، هرکجا عدد مانیفست ذکر شده است تعداد کل افراد آن مانیفست ها هم درج شود.

توضیحات تکمیلینیاز است.
@mehabadi 
![2017-05-17_17-26-47](https://cloud.githubusercontent.com/assets/28531483/26154904/91a84748-3b26-11e7-9cad-7f71a634736d.jpg)

Dear @jafarzadeh @ehsmohammadi,
Do you agree with their request?!!
In my opinion we need to remove some parts of dashboard panel and prepare Haj Organization with the proper reports.

**Comment by mmahabadi** [comment]
مورد 26
نمایش اسامی استانها زیر نمودار از حالت افقی به حالت عمودی

توضیحات کاملتر 

@mehabadi 
![2017-05-17_12-14-37](https://cloud.githubusercontent.com/assets/28531483/26154996/f56bdb3c-3b26-11e7-96d5-79fa752d5878.jpg)

**Comment by ehsmohammadi** [comment]
All the question was surveyed by our support and analyses team and will be answered today

**Comment by fAllahyari** [comment]
![1](https://cloud.githubusercontent.com/assets/27915531/26274405/ac720e58-3d5e-11e7-8c3d-57701b9a87cc.png)
![2](https://cloud.githubusercontent.com/assets/27915531/26274407/ae1eaa7c-3d5e-11e7-884f-f0402bb0a5d1.png)
![3](https://cloud.githubusercontent.com/assets/27915531/26274408/afc63ad4-3d5e-11e7-923d-6d99882bfcaa.png)

**Comment by Morebopo** [comment]
@fAllahyari 
مورد 11، در جابجایی کارگزاری، حق کارگزار به کارگزار دوم که در جابجایی ثبت میشود میرود، ایا این درست است؟
بله دقیقاً به همین نحو است، حق کارگزار به کارگزار دوم تعلق پیدا می کند
