### ISSUE TITLE
System exception and user exception message must be checked ( Item 9 ) 

### ISSUE THREAD

**Issue by emoradi** [ehsmohammadi/Atabat#44]
مورد 9 : اصلاح نمودن پیام های سیستم به صورتی که پیام در بر گیرنده و مشخص کننده خطای ایجاد شده در سیستم باشد

**Comment by msabeti** [comment]
این مسئله به علت همزمانی ورود دو رکورد جدول کاور پیش آمده بود( مشکل EF) که موقتا با  job  رفع شده.
