### ISSUE TITLE
Implement YEKE problem ( item 12 ) 

### ISSUE THREAD

**Issue by ehsmohammadi** [ehsmohammadi/Atabat#53]
@fAllahyari  please provide your code and research here so i can continue it

**Comment by ehsmohammadi** [comment]
http://www.dotnettips.info/post/1745/%DB%8C%DA%A9-%D8%AF%D8%B3%D8%AA-%D8%B3%D8%A7%D8%B2%DB%8C-%DB%8C-%D9%88-%DA%A9-%D8%AF%D8%B1-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87%E2%80%8C%D9%87%D8%A7%DB%8C-entity-framework-6

**Comment by ehsmohammadi** [comment]
After i read above link i found another link that might be useful in out context 

http://www.dotnettips.info/post/844/ef-code-first-14

After read and use this link i have some problem that i must resolve in order to apply this bug fix

**Comment by ehsmohammadi** [comment]
After i found the link and implement the classes i made some change because of using object context instead of dbcontext in this project 
I check in this code and @fAllahyari  continue our work ..

**Comment by fAllahyari** [comment]
سه فیلد نام و نام خانوادگی و محل صدور شناسنامه تصحیح میشود و بعد در دیتابیس ذخیره میشود.
در ادمین هم موقع جستجو قبل از سرچ نام تصحیح میشود

با تگ 
//YEKE
انجام شد که بعدا بشود تغییر داد.
در لایه 
EF
انجام شد
changeset 18275
it tack 3 hour
@mehabadi @ehsmohammadi 

این مورد تا انجام 
codefirst
باز می ماند

**Comment by fAllahyari** [comment]
.آپدیت اطلاعات موجود در دیتابیس
کوئری مربوطه در 
SeedData.sql
اضافه شد

**Comment by ehsmohammadi** [comment]
@fAllahyari we must talk about this adjustment so we can fix this problem on server too

**Comment by ehsmohammadi** [comment]
I must check what can i do for this problem , Should I implement the solution in frame work or not ??
??

**Comment by fAllahyari** [comment]
framework changed
@mehabadi @msabeti @MarziyehK @emoradi @FeSaeedi 
please use  sic.core.yeke.CurrectYeKe
