### ISSUE TITLE
has multiple visa type In not special period 

### ISSUE THREAD

**Issue by fAllahyari** [ehsmohammadi/Atabat#55]
آیا ویزای مالتی پل در ایام عادی داریم؟ در ایام خاص چطور؟
با توجه به اینکه در دوره قبل ویزای مالتی پل کلا نداشتیم

**Comment by fAllahyari** [comment]
please answer in new comment

**Comment by ehsmohammadi** [comment]
@fAllahyari 
الویت نیست و اینکه باتوجه به اینکه دوره های قبل به کار نیومد، فعلا نیازی نیست
