### ISSUE TITLE
Developing and debugging Facility in Period

### ISSUE THREAD

**Issue by mmahabadi** [ehsmohammadi/Atabat#56]
Developing Facility changes in admin panel.

Following Stored procedures has been changed:
- sp_Reports_GetDashboarsReports

**Comment by ehsmohammadi** [comment]
@mehabadi  
This store procedures have bug : 
sp__report_DashboardRegitrationInformation
sp_GetArzTransferenceDocSummaries
sp_Reports_ConnectorData
sp_Reports_GetGroupsApplicantsByGroupID
sp_UpdateArzTransferenceDocSummaries

**Comment by mmahabadi** [comment]
Remove FacilityCostController and related files.

**Comment by mmahabadi** [comment]
Dear @ehsmohammadi,

sp__report_DashboardRegitrationInformation is not used.
sp_Reports_ConnectorData is written by @msabeti.
Other ones are repaired.
