### ISSUE TITLE
How to Implement Facility Cost in each state

### ISSUE THREAD

**Issue by fAllahyari** [ehsmohammadi/Atabat#59]
هنگام تغییر قیمت سرویسها  در مواقع مختلف مانند اضافه شدن فرد به گروه یا اتفاقاتی از این قبیل کدام قیمت سرویس باید در نظر گرفته شود؟  

این گونه تصمیم گرفته شد که یک متد محاسبه مجدد قیمت های سرویس در تمام وضعیت ها داشته باشیم و آن را در تغییرات گروه یا... صدا کنیم.
قبل از پرداخت، قیمت به قیمت های جدید بروز می شود و اگر تغییری داشت نشان میدهد و بعد به درگاه میرود.
هنگام اضافه شدن فرد به گروه در وضعیت 2 اگر قیمت سرویس به تعداد نفرات بستگی داشت، قیمت های دیگر افراد  نیز تغییر میکند.

**Comment by jafarzadeh** [comment]
ضمنا قرار شد سازمان حج رو ترغیب و قانع کنیم که این روش محاسبه هزینه (هزینه خدمات بر اساس روز) رو قبول کنه
------------
همچنین قرار شد در صورتیکه گروه در وضعیت های بعد از 2 بود یعنی پرداخت شده به بعد در صورتیکه نیاز به بروز شدن هزینه ها باشد و تعیین مابه التفاوت شد مابه اتفاوت را برای خدمت مربوطه طبق هزینه روز محاسبه کنیم

**Comment by FeSaeedi** [comment]
البته  در وضعیت های بعد از 2 ، در صورتی که سطح گروه عوض شده باشد قیمت های بروز میشود در غیر این صورت تغییر نمی کند
