### ISSUE TITLE
Rial field update to decimal(18,0) from bigint

### ISSUE THREAD

**Issue by fAllahyari** [ehsmohammadi/Atabat#60]
فیلد هزینه ریالی از 
bigint
به
decmila(18,0)
تغییر یافت در جداول زیر:
FacilityCosts
Group_Facilities_Applicants
paymentLog

لطفا در جداول دیگر هم اگر با این فیلد کار میکنید نوع آن را یکسان سازی نمایید.
@mehabadi @emoradi  @msabeti @FeSaeedi

**Comment by fAllahyari** [comment]
ArzValue field in ArzValuesTable chang from decimal(19, 1) To decimal(19, 2)

**Comment by fAllahyari** [comment]
MergedFacilityLogs
MergedPaymentLogs

currected

**Comment by fAllahyari** [comment]
Checkin changeset 18264
@emoradi @mehabadi @msabeti @FeSaeedi

**Comment by ehsmohammadi** [comment]
@fAllahyari if there no thing to be done in this issue please close it ..

**Comment by fAllahyari** [comment]
لطفا در کدهای خود نوع داده ریال و دلار را چک نمایید 
@emoradi @mehabadi @msabeti @FeSaeedi
