### ISSUE TITLE
Implement new infrastructure for create and migrate Database

### ISSUE THREAD

**Issue by ehsmohammadi** [ehsmohammadi/Atabat#61]
By closing this issue and considering all changed that we have faced I want to implement this feature for samah project 
https://github.com/ehsmohammadi/InfraStructure/issues/9

**Comment by ehsmohammadi** [comment]
- vw_VizaCount has error in migrating process 
- this item was removed from view

**Comment by ehsmohammadi** [comment]
Error in migration process : 
sp__report_DashboardRegitrationInformation
sp_GetArzTransferenceDocSummaries
sp_Reports_ConnectorData
sp_Reports_GetGroupsApplicantsByGroupID
sp_UpdateArzTransferenceDocSummaries

**Comment by ehsmohammadi** [comment]
All thing in order now just fix this issue and generate script file is needed

**Comment by fAllahyari** [comment]
vw_province not used. i removed it from code

view sabteAhvalError not used in code but it use for sabte ahval error report raised from sabteAhval company

it is take 1 hour

**Comment by ehsmohammadi** [comment]
Migration is ready waiting for testing by all developer

**Comment by fAllahyari** [comment]
please notice fllowing points in query:

update [AtabatVisa].[dbo].[SystemSettings] set Value='2018/11/16 23:59:00' where id=21
go
update [AtabatVisa].[dbo].[SystemSettings] set Value='2018/11/16 23:59:00' where id=13
go
update [AtabatVisa].[dbo].[SystemSettings] set Value='2018/11/16 23:59:00' where id=14
go
update [AtabatVisa].[dbo].[RegistrationTimePeriods_Provinces] set IsActive=1 where RegistrationTimePeriodID=4
go
insert into [AtabatVisa].[dbo].[RegistrationTimePeriods_Provinces]([ProvinceID]
,[RegistrationTimePeriodID]
,[IsActive]) select ID,6,0 from [AtabatVisa].[dbo].Provinces where CountryID=1
go
update [AtabatVisa].[dbo].[RegistrationTimePeriods_Provinces] set IsActive=1 where RegistrationTimePeriodID=6 and ProvinceID in ( 19,15,17,20)
go
update [AtabatVisa].[dbo].[RegistrationTimePeriod] set IsActive=0 where id=4
go
update [AtabatVisa].[dbo].[SystemSettings] set Value='2018/11/16 23:59:00' where id=21
go
  update [AtabatVisa].[dbo].[RegistrationTimePeriods_Provinces] set IsActive=1 where RegistrationTimePeriodID=4
  go
  insert into [AtabatVisa].[dbo].[RegistrationTimePeriods_Provinces]([ProvinceID]
      ,[RegistrationTimePeriodID]
      ,[IsActive]) select ID,6,0 from [AtabatVisa].[dbo].Provinces where CountryID=1
go
  update [AtabatVisa].[dbo].[RegistrationTimePeriods_Provinces] set IsActive=1 where RegistrationTimePeriodID=6 and ProvinceID in ( 19,15,17,20)
  go
   update [AtabatVisa].[dbo].[RegistrationTimePeriod] set OpenForPayment=1, paymenttype=3 where id=6

**Comment by fAllahyari** [comment]
for delete registration data before state=2 this below query be helpfull
declare @gid int=1090694
 delete FROM [AtabatVisa].[dbo].[Groups]  where id=@gid

 delete  from Group_Facilities_Applicants where groupid=@gid
  
 delete from  paymentLogs where GroupID=@gid
 delete  from MergedGroups where MasterGroupID=@gid or SlaveGroupID=@gid
 delete  from GroupStateLogs where GroupID=@gid
 delete  from Groups_stations where GroupID=@gid
 delete  from covers_groups where GroupID=@gid
 delete  from GeneralApplicant where id=@gid
 delete from Applicants where GroupID=@gid

**Comment by ehsmohammadi** [comment]
this link is described how we can use fluent migrator in action : 
https://benpowell.org/deploying-database-migrations-in-net-using-fluentmigrator-teamcity-and-octopus-deploy/

**Comment by ehsmohammadi** [comment]
I must wiki this rule and instruction for new or slack developer
