### ISSUE TITLE
Close DateTime in Period

### ISSUE THREAD

**Issue by FeSaeedi** [ehsmohammadi/Atabat#71]
در طی دو سال اخیر چند تا تاریخ مربوط به بسته شدن ثبت نام در دوره به جود امده::
1 بسته شدن ثبت نام عمومی و باز بودن ثبت نام تنها توسط کارگزاری ها
2 بسته شدن ثبت نام
3 بسته شدن ویرایش
مورد اول بنا به نیاز سازمان در سال 95 و مورد دوم و سوم در سال 94 به وجود امدند.
در حال حاضر ترتیب این تاریخ ها و نحوه چک کردن باز یا بسته بودن سیستم چگونه باید چک شود؟؟؟

**Comment by ehsmohammadi** [comment]
@FeSaeedi  in previous meeting this question was answered , please provide us with those answer here

**Comment by FeSaeedi** [comment]
طبق دوران گذشته، با خانم الهیاری به این جمع بندی رسیدیم:
در طول دوره ثبت نام، از ابتدا، ثبت نام توسط عموم و کارگزاری ها  انجام میگیرد. 
ثبت نام توسط عموم تا تاریخ 
CloseRegisterationTime
و توسط کارگزاری ها نیز تا تاریخ 
CloseRegisterForAgents
باز خواهد بود.
