### ISSUE TITLE
Question about multi registration data

### ISSUE THREAD

**Issue by fAllahyari** [ehsmohammadi/Atabat#72]
اگر فردی در یک دوره زمانی ثبت نام کرده است و میخواهد در یک دوره دیگر هم ثبت نام کند،  اطلاعات تماس 
(contactInfo)
آن روی اطلاعات قبلی نوشته میشود
آیا این درست است یا نیاز به اصلاح طراحی دارد؟
پیشنهاد اینجانب این است که استان محل تحویل مدارک اضافه شود که با استان محل سکونت فرق داشته باشد و اطلاعات تماس همیشه یکی باشد.

**Comment by ehsmohammadi** [comment]
@fAllahyari we had meeting about this question and all your question was answered please provide every one with the answer here 
thank you in advance

**Comment by fAllahyari** [comment]
بنا بر بند 27 نامه شماره2962 مورخ 96/02/17 ، امکان ویرایش استان محل تحویل مدارک
مقرر شد که استان محل تحویل مدارک در صفحه ثبت نام اضافه شود که این استان مبنای گزارشات است و با استانهای 
 فعال در پریود پر میشود. استان محل سکونت هم تمامی استانها را نشان میدهد و در تمامی ثبت نام ها یکی است به این معنا که اگر درثبت نام در دو دوره فعال اگر استان محل سکونت تغییر کند در تمام ثبت نامها تغییر میکند

**Comment by fAllahyari** [comment]
depend on #3
