### ISSUE TITLE
Question About minAppCount inProvince

### ISSUE THREAD

**Issue by fAllahyari** [ehsmohammadi/Atabat#81]
هنگام ست نمودن استان محل تحویل مدارک، چک میشد که این استان به کدام کنسولگری متصل است و در آن کنسولگری حداقل اعضای گروه چند نفر میباشد.
اکنون که هر استان میتواند چند کنسولگری داشته باشد این شرط چگونه چک شود؟

**Comment by Morebopo** [comment]
پیرو مذاکره با آقای میر احمدیان مقرر شد ، اطلاع بدهند، در حال پیگیری

**Comment by fAllahyari** [comment]
حداقل مقدار چک میشود
