### ISSUE TITLE
Fixing Person History bug

### ISSUE THREAD

**Issue by mmahabadi** [ehsmohammadi/Atabat#97]
20. در پنل مدیر سیستم در منوی ثبت نام های فرد پس از زدن کلید مشاهده اطلاعات گروه با خطای 500 مواجه می شویم.

**Comment by MarziyehK** [comment]
در solution-dev موردی مشاهده نشد، 
در solution main به علت عدم register کردن دو interface خطا ایجاد شده بود  که رفع گردید.
